# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

  - script: mkdir $(build.artifactstagingdirectory)/git-secrets
    displayName: 'Create empty directory for git-secrets clone'

  - script: git clone https://github.com/awslabs/git-secrets $(build.artifactstagingdirectory)/git-secrets
  displayName: 'Clone git-secrets'

  - script: cd $(build.artifactstagingdirectory)/git-secrets; sudo make install;
  displayName: 'Make git-secrets install'

  - script: cd $(Build.Repository.LocalPath);git secrets --register-aws;git secrets --scan
  displayName: 'Scan pipeline repo for secrets'

  - script: echo 'Scan for secrets passed, continue.'
  displayName: 'Scan for secrets passed, continue'

