# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ScanForSecrets
    dependsOn: []
    jobs:
      - job: GittyLeaks
        steps:
        - script: pip3 install gittyleaks 
          displayName: 'Install gittyleaks'

        - script: cd $(Build.Repository.LocalPath);gittyleaks
          displayName: 'Scan pipeline repo for secrets'
  - stage: ContinueBuild
    dependsOn:
      - ScanForSecrets
    jobs:
      - job: NextJob
        steps:
        - script: echo 'Scan for secrets passed, continue.'
          displayName: 'Scan for secrets passed, continue'
