# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: pip install gittyleaks
    displayName: 'Install gitty leaks'

  - script: cd $(Build.Repository.LocalPath);gittyleaks
  displayName: 'Scan pipeline repo for secrets'

  - script: echo 'Scan for secrets passed, continue.'
  displayName: 'Scan for secrets passed, continue'

